micronaut:
  application:
    name: securejwt
  security:
    enabled: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: mysecret
  server:
    port: 5555
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/rimfirededb?currentSchema=jwt_auth
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: rimfirededb
    password: mysecretpassword
